@url = https://mdapi.sreenaina.com/api

###
GET {{url}}/courses HTTP/1.1

###
PUT {{url}}/courses HTTP/1.1
content-type: application/json

{
    "id": "CS306-001",
    "credits": 3,
    "name": "Synt Ethics/Law for Comp Professionals",
    "professor": "Tamara Maddox",
    "days": [
        {"Tue": ["9:00 AM", "10:15 AM"] },
        {"Thu": ["9:00 AM", "10:15 AM"] }
    ],
    "location": "Nguyen Engineering Building",
    "prerequisites": ["CS110"],
    "type": "lecture",
    "room": "1107"
}

###
GET {{url}}/students HTTP/1.1

###
PUT {{url}}/students HTTP/1.1
content-type: application/json

{
    "id": "G01280318",
    "name": "Gulsima Karsli",
    "email": "gkarsli@gmu.edu",
    "finishedcourses": ["CS110-001", "CS112-001", "CS211-001", "CS262-001", "CS310-002"],
    "courses": ["CS321-002", "CS367-004", "CS330-005"],
    "futurecourses": ["CS483-002", "CS306-001", "CS471-001"],
    "advisor": "Brian Hrolenok",
    "major": "Computer Science",
    "year": "Junior",
    "enrollment": "full-time",
    "term": "Spring 2024",
    "graduation": "Fall 2025",
    "gpa": "3.75"
}







